
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 06 01:48:44 BRT 2016
//----------------------------------------------------

package analise_sintatica;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int ATTRIB = 18;
  public static final int CONS = 3;
  public static final int FUNCTION = 5;
  public static final int MULT = 29;
  public static final int LPAREN = 10;
  public static final int INT = 20;
  public static final int MINUS = 28;
  public static final int RPAREN = 11;
  public static final int AND = 36;
  public static final int NOT = 35;
  public static final int SEMICOLON = 16;
  public static final int LTHAN = 34;
  public static final int OR = 37;
  public static final int BOOL = 22;
  public static final int COMMA = 17;
  public static final int DIV = 30;
  public static final int PLUS = 27;
  public static final int IF = 6;
  public static final int EOF = 0;
  public static final int TRUE = 25;
  public static final int error = 1;
  public static final int MOD = 31;
  public static final int EQ = 32;
  public static final int LBRACK = 12;
  public static final int REAL = 21;
  public static final int GTHAN = 33;
  public static final int LBRACE = 14;
  public static final int ELSE = 8;
  public static final int TQ = 19;
  public static final int INTEIRO = 23;
  public static final int RBRACK = 13;
  public static final int WHILE = 9;
  public static final int FLOAT = 24;
  public static final int THEN = 7;
  public static final int RBRACE = 15;
  public static final int FALSE = 26;
  public static final int VAR = 2;
  public static final int PROCEDURE = 4;
  public static final int IDENTIFIER = 38;

  /* non terminals */
  static final int dec_cons_list = 28;
  static final int bloco_comandos = 24;
  static final int tipo = 6;
  static final int inicializacao = 9;
  static final int list_var_inic_opt = 8;
  static final int bloco = 21;
  static final int exp = 25;
  static final int exp_list_opt = 30;
  static final int bloco_com = 22;
  static final int array_comp_opt = 13;
  static final int exp_list = 29;
  static final int bloco_comandos_list = 23;
  static final int Programa = 0;
  static final int bloco_exp = 27;
  static final int inic_opt = 10;
  static final int dec_list = 1;
  static final int parametros = 14;
  static final int dec_var = 2;
  static final int chamada = 31;
  static final int array_comp = 12;
  static final int lista_param = 15;
  static final int array_ext = 11;
  static final int dec_procedimento = 4;
  static final int variable = 20;
  static final int assign = 19;
  static final int parametro = 16;
  static final int dec_cons = 3;
  static final int simple_exp = 26;
  static final int comando_esp = 18;
  static final int dec_funcao = 5;
  static final int comando = 17;
  static final int tipo_base = 7;
}

