
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 03 20:26:09 BRT 2016
//----------------------------------------------------

package analise_lexica;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int ATTRIB = 15;
  public static final int CONS = 3;
  public static final int FUNCTION = 12;
  public static final int MULT = 27;
  public static final int LPAREN = 20;
  public static final int INT = 4;
  public static final int MINUS = 26;
  public static final int RPAREN = 21;
  public static final int NOT = 33;
  public static final int SEMICOLON = 14;
  public static final int AND = 34;
  public static final int LTHAN = 32;
  public static final int OR = 35;
  public static final int BOOL = 6;
  public static final int COMMA = 13;
  public static final int DIV = 28;
  public static final int PLUS = 25;
  public static final int IF = 7;
  public static final int EOF = 0;
  public static final int TRUE = 23;
  public static final int error = 1;
  public static final int MOD = 29;
  public static final int EQ = 30;
  public static final int LBRACK = 16;
  public static final int REAL = 5;
  public static final int GTHAN = 31;
  public static final int LBRACE = 18;
  public static final int ELSE = 9;
  public static final int INTEIRO = 36;
  public static final int TQ = 22;
  public static final int RBRACK = 17;
  public static final int WHILE = 10;
  public static final int FLOAT = 37;
  public static final int THEN = 8;
  public static final int RBRACE = 19;
  public static final int FALSE = 24;
  public static final int VAR = 2;
  public static final int PROCEDURE = 11;
  public static final int IDENTIFIER = 38;
}

